---
kind: pipeline
name: build-on-amd64-fedora29

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  commands:
  - docker build -t bpftrace-builder-amd64-fedora29 -f docker/Dockerfile.fedora29 docker/

trigger:
  branch:
  - ci
  event:
  - push

---
kind: pipeline
name: build-on-amd64-ubuntu

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  commands:
  - docker build -t bpftrace-builder-amd64-ubuntu -f docker/Dockerfile.ubuntu docker/

trigger:
  branch:
  - ci
  event:
  - push

---
kind: pipeline
name: build-on-arm64-fedora29

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: docker
  commands:
  - docker build -t bpftrace-builder-arm64-fedora29 -f docker/Dockerfile.fedora29 docker/

trigger:
  branch:
  - ci
  event:
  - push

---
kind: pipeline
name: build-on-arm64-ubuntu

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: docker
  commands:
  - docker build -t bpftrace-builder-arm64-ubuntu -f docker/Dockerfile.ubuntu docker/

trigger:
  branch:
  - ci
  event:
  - push

...
